<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:p4="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ITV">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Param">
					<xs:complexType>
						<xs:sequence>
							<xs:element minOccurs="0" name="PAR_ExportDate" nillable="true"    type="xs:dateTime"  />
							<xs:element name="Project">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="PRO_Language" type="xs:string" />
									</xs:sequence>
									<xs:attribute name="PRO_Code" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="Country">
								<xs:complexType>
									<xs:attribute name="CTY_code" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element minOccurs="0" name="MS_Version" nillable="true" type="xs:string"  />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="ListeInterviews">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" name="Interview">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="ITV_Id" minOccurs="0" nillable="true" />
										<xs:element name="ITV_RecallDate" type="xs:dateTime" />
										<xs:element name="CTR_Code" type="xs:string" />
										<xs:element name="ITR_Code" type="xs:string" />
										<xs:element name="ITR_CTY_Code" type="xs:string" />
										<xs:element name="ITR_CTR_Code" type="xs:string" />
										<xs:element name="SBT_Code" type="xs:string" />
										<xs:element name="SBT_Name" type="xs:string" />
										<xs:element name="SBT_FirstName" type="xs:string" />
										<xs:element name="SBT_Sex" type="xs:unsignedByte" />
										<xs:element name="SBT_BirthDate" type="xs:dateTime" />
										<xs:element name="ITG_Release" type="xs:dateTime" />
										<xs:element name="ITG_Num" type="xs:unsignedShort" />
										<xs:element name="ITG_Date" type="xs:dateTime" />
										<xs:element name="ITG_SubjectHeight" type="xs:double" />
										<xs:element name="ITG_SubjectWeight" type="xs:double" />
										<xs:element name="ITG_VURecall" type="xs:string" />
										<xs:element name="ITG_VUNextRecall" type="xs:string" />
										<xs:element name="ITG_EnergyRequirement" type="xs:double" />
										<xs:element name="ITG_EnergyCalculated" type="xs:double" />
										<xs:element name="ITG_TimeGI" type="xs:string" />
										<xs:element name="ITG_TimeQL" type="xs:string" />
										<xs:element name="ITG_TimeDQ" type="xs:string" />
										<xs:element name="ITG_TimeDS" type="xs:string" />
										<xs:element name="ITG_TimeALL" type="xs:string" />
										<xs:element name="ITG_RecomputeDate" type="xs:dateTime" />
										<xs:element name="ITG_SPD_code" type="xs:string" />
										<xs:element name="ITG_SPT_code" type="xs:string" />
										<xs:element name="ITG_Version" type="xs:string" minOccurs="0"/>
										<xs:element minOccurs="0" name="ListeNotes">
											<xs:complexType>
												<xs:sequence minOccurs="0" >
													<xs:element minOccurs="0" maxOccurs="unbounded" name="Note">
														<xs:complexType >
															<xs:sequence minOccurs="0">
																<xs:element name="NOT_Status" minOccurs="0" type="xs:string" />
																<xs:element name="NOT_Memo" minOccurs="0" type="xs:string" />
																<xs:element name="NOT_Date" minOccurs="0" type="xs:dateTime" />
																<xs:element name="NOT_Label" minOccurs="0" type="xs:string"  nillable="true" default="-"/>
																<xs:element name="NOT_Type" minOccurs="0" type="xs:string" nillable="true" default="-"/>
																<xs:element name="NOT_QuantityConsumed" minOccurs="0" type="xs:double" />
																<xs:element name="NOT_MaxVal" minOccurs="0" type="xs:boolean" />
																<xs:element name="NOT_EmptyQLI" minOccurs="0" type="xs:boolean" />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element minOccurs="0" name="ListeLignesITV">
											<xs:complexType>
												<xs:sequence minOccurs="0">
													<xs:element minOccurs="0" maxOccurs="unbounded" name="LigneITV">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="ITL_POC_Code" type="xs:unsignedByte" />
																<xs:element name="ITL_FCO_Code" type="xs:unsignedByte" />
																<xs:element name="ITL_FCOHour" type="xs:short" />
																<xs:element name="ITL_TOK" type="xs:double" />
																<xs:element name="ITL_QLINUM" type="xs:double" />
																<xs:element name="ITL_ING_NUM" type="xs:double" />
																<xs:element name="ITL_S_ING_NUM" type="xs:double" />
																<xs:element name="ITL_Type" type="xs:string" />
																<xs:element minOccurs="0" name="ITL_FoodNum" type="xs:string" />
																<xs:element minOccurs="0" name="ITL_Group" type="xs:string" />
																<xs:element minOccurs="0" name="ITL_SubGroup1" type="xs:string" />
																<xs:element minOccurs="0" name="ITL_SubGroup2" type="xs:string" />
																<xs:element minOccurs="0" name="ITL_DS_Classif" type="xs:string" />
																<xs:element minOccurs="0" name="ITL_F_Type" type="xs:string" />
																<xs:element minOccurs="0" name="ITL_I_Type" type="xs:string" />
																<xs:element minOccurs="0" name="ITL_R_Modif" type="xs:unsignedByte" />
																<xs:element minOccurs="0" name="ITL_I_Modif" type="xs:unsignedByte" />
																<xs:element minOccurs="0" name="ITL_R_Type" type="xs:string" />
																<xs:element name="ITL_Text" type="xs:string" />
																<xs:element minOccurs="0" name="ITL_Name" type="xs:string" />
																<xs:element minOccurs="0" name="ITL_Facets_STR" type="xs:string" />
																<xs:element minOccurs="0" name="ITL_BrandName" type="xs:string" />
																<xs:element minOccurs="0" name="ITL_Status" type="xs:string" />
																<xs:element name="ITL_Estim_QTY" type="xs:double" />
																<xs:element minOccurs="0" name="ITL_Q_Method" type="xs:string" />
																<xs:element minOccurs="0" name="ITL_QM_Code" type="xs:string" />
																<xs:element minOccurs="0" name="ITL_QUNIT" type="xs:string" />
																<xs:element name="ITL_NGRAMS" type="xs:double" />
																<xs:element minOccurs="0" name="ITL_Proport" type="xs:string" />
																<xs:element minOccurs="0" name="ITL_HHMFract" type="xs:string" />
																<xs:element minOccurs="0" name="ITL_R_Fract" type="xs:string" />
																<xs:element minOccurs="0" name="ITL_RawCooked" type="xs:unsignedByte" />
																<xs:element minOccurs="0" name="ITL_ConsRawCo" type="xs:unsignedByte" />
																<xs:element name="ITL_Conver" type="xs:double" />
																<xs:element minOccurs="0" name="ITL_EDIB" type="xs:unsignedByte" />
																<xs:element name="ITL_EDIB_CSTE" type="xs:double" />
																<xs:element name="ITL_DENSITY" type="xs:double" />
																<xs:element name="ITL_FATLEFTO" type="xs:boolean" />
																<xs:element name="ITL_FAT_PCT" type="xs:double" />
																<xs:element name="ITL_PCT_CONS" type="xs:double" />
																<xs:element name="ITL_PCT_ESTIM" type="xs:double" />
																<xs:element name="ITL_CONS_QTY" type="xs:double" />
																<xs:element name="ITL_R_COOKED" type="xs:double" />
																<xs:element name="ITL_R_EDIB" type="xs:double" />
																<xs:element name="ITL_RAW_Q" type="xs:double" />
																<xs:element name="ITL_RAW_Q_W" type="xs:double" />
																<xs:element name="ITL_MAX" type="xs:unsignedByte" />
																<xs:element name="ITL_SUPPL" type="xs:boolean" />
																<xs:element name="ITL_ITEM_SEQ" type="xs:int" />
																<xs:element name="ListeITV_Quantity">
																	<xs:complexType>
																		<xs:sequence minOccurs="0">
																			<xs:element maxOccurs="unbounded" name="ITV_Quantity_Service">
																				<xs:complexType>
																					<xs:sequence>
																						<xs:element name="ITQ_Order" type="xs:double" />
																						<xs:element minOccurs="0" name="ITQ_SH_Code" type="xs:string" />
																						<xs:element name="ITQ_SH_Surface" type="xs:double" />
																						<xs:element minOccurs="0" name="ITQ_TH_Code" type="xs:string" />
																						<xs:element minOccurs="0" name="ITQ_TH_Thick" type="xs:double" />
																						<xs:element minOccurs="0" name="ITQ_PH_Code" type="xs:string" />
																						<xs:element minOccurs="0" name="ITQ_PH_QTY" type="xs:double" />
																						<xs:element name="ITQ_FRACT" type="xs:string" />
																					</xs:sequence>
																				</xs:complexType>
																			</xs:element>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
																<xs:element name="ListeITV_Nutriments">
																	<xs:complexType>
																		<xs:sequence minOccurs="0">
																			<xs:element maxOccurs="unbounded" name="ITV_Nutriment">
																				<xs:complexType>
																					<xs:sequence>
																						<xs:element name="NTR_Code" type="xs:int" />
																						<xs:element name="ITV_NTR_Value" type="xs:double" />
																					</xs:sequence>
																				</xs:complexType>
																			</xs:element>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
																<xs:element minOccurs="0" name="ListeNotes">
																	<xs:complexType>
																		<xs:sequence minOccurs="0" >
																			<xs:element minOccurs="0" maxOccurs="unbounded" name="Note">
																				<xs:complexType >
																					<xs:sequence minOccurs="0">
																						<xs:element name="NOT_Status" minOccurs="0" type="xs:string" />
																						<xs:element name="NOT_Memo" minOccurs="0" type="xs:string" />
																						<xs:element name="NOT_Date" minOccurs="0" type="xs:dateTime" />
																						<xs:element name="NOT_Label" minOccurs="0" type="xs:string"  nillable="true" default="-"/>
																						<xs:element name="NOT_Type" minOccurs="0" type="xs:string" nillable="true" default="-"/>
																						<xs:element name="NOT_QuantityConsumed" minOccurs="0" type="xs:double" />
																						<xs:element name="NOT_MaxVal" minOccurs="0" type="xs:boolean" />
																						<xs:element name="NOT_EmptyQLI" minOccurs="0" type="xs:boolean" />
																					</xs:sequence>
																				</xs:complexType>
																			</xs:element>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
